---
- name: Copy firewall ip6tables
  template: 
    src: ip6tables.j2
    dest: "{{ ip6tables_file }}"
    owner: root 
    group: root
    mode: 0644
    backup: true
  notify: restart ip6tables
  register: ip6tables_file_out
  when: configure_firewall | default(true)
  tags: firewall

- name: Check ip6tables syntax
  when: ip6tables_file_out.changed and ( configure_firewall | default(true) )
  tags: firewall
  block:
    - name: Check ip6tables syntax
      command: "{{ ip6tables_check_syntax_command }}"
  rescue:
    - name: Read ip6tables file content before reverting
      shell: cat {{ ip6tables_file }}
      register: remove_ip6tables_content

    - name: Content of ip6tables file with incorrect syntax
      debug: 
        msg: "{{ remove_ip6tables_content.stdout }}"

    - name: Revert ip6tables file content
      copy: 
        remote_src: True # move
        src: "{{ ip6tables_file_out.backup_file }}"
        dest: "{{ ip6tables_file }}"

    - fail:
        msg: There is a syntax error on {{ ip6tables_file }} file. We've reverting it. Check content previously printed.
