- name: Real restarting ip6tables service
  service: 
    name: "{{ ip6tables_service }}"
    state: restarted

- name: Check If Docker Is Installed
  command: docker --version
  register: docker_valid
  ignore_errors: yes

- name: Define variable if docker is installed
  set_fact:
    docker_is_installed: "{{ not docker_valid.failed }}"

- name: Print debug message saying if docker is or not installed
  debug:
    msg: "docker is {{ '' if docker_is_installed else 'NOT ' }}installed on {{ inventory_hostname }} server"

- name: Restart docker service after iptables restart
  service:
    name: docker
    state: restarted
  when: docker_is_installed
